# Generated by Django 5.0.6 on 2024-12-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_cosmobloguser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
